converting to posix sh

diff --git a/private_dot_local/bin/executable_dropbadips b/private_dot_local/bin/executable_dropbadips
--- a/private_dot_local/bin/executable_dropbadips
+++ b/private_dot_local/bin/executable_dropbadips
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/bin/sh
 # dropbadips processes mox mail server log files to identify obvious bad actors
 # and add a DROP rule for their IP.
 #
@@ -32,6 +32,12 @@ logger "$SCRIPT starting, command line parameter [$1]"
 
 . /etc/os-release
 case $ID in
+chimera)
+    LOGCURRENT="cat /var/log/mox.log"
+    # TODO until logrotate happens
+    LOGALL="cat /var/log/mox.log"
+    # LOGALL="cat /var/log/socklog/messages/@* /var/log/socklog/messages/current"
+    ;;
 void)
     LOGCURRENT="cat /var/log/socklog/messages/current"
     LOGALL="cat /var/log/socklog/messages/@* /var/log/socklog/messages/current"
@@ -50,7 +56,12 @@ esac
 SCOPE=$LOGCURRENT
 
 install() {
+    . /etc/os-release
     case $ID in
+    chimera)
+        cp $SCRIPT /usr/bin/$BASE
+        chmod +x /usr/bin/$BASE
+        ;;
     void)
         # ensure the latest is installed in hourly
         # Note: Void/runit run-parts command won't launch a script ending in .sh
@@ -76,8 +87,8 @@ block_countries() {
     for code in $COUNTRIES; do
         logger "$BASE dropping country $code"
         URL="$BASE_URL$code$URL_SUFFIX"
-        for ip in $(curl $URL); do
-            iptables -A INPUT -j DROP -s $ip
+        for ip in $(curl "$URL"); do
+            iptables -A INPUT -j DROP -s "$ip"
         done
     done
 }
@@ -88,28 +99,27 @@ block_countries() {
 # - reset: drop current iptables, import any countries defined, and process all the log files current and past
 #          reset may get run once on boot
 if [ ! $# -eq 0 ]; then
-    if [ "$1" == "install" ]; then
+    if [ "$1" = "install" ]; then
         install
         echo "Installed, exiting"
         exit
-    elif [ "$1" == "all" ]; then
+    elif [ "$1" = "all" ]; then
         SCOPE=$LOGALL
         logger "$BASE scanning all logs"
-    elif [ "$1" == "reset" ]; then
+    elif [ "$1" = "reset" ]; then
         # no params after reset
-        if [ "$2" == "" ]; then
+        if [ "$2" = "" ]; then
             echo "$BASE reset: requires at least one country code as parameter"
             echo "eg: $BASE reset ru cn"
             exit
         fi
         logger "$BASE resetting iptables"
         iptables -F
-        # after arg 1, balanace are countries
+        # after arg 1, any remaining args are countries
         shift
         COUNTRIES=""
         for var in "$@"; do
-            COUNTRIES+=" "
-            COUNTRIES+="$var"
+            COUNTRIES="${COUNTRIES:+${COUNTRIES} }${var}"
         done
         logger "$BASE dropping countries: $COUNTRIES"
         block_countries
@@ -148,9 +158,9 @@ done
 # TIME TO DROP IPs
 # all other rules are APPENDED
 # mail system, failed auth
-for ip in $($SCOPE | grep "mox.*failed auth" | awk -F 'remote=| cid' '{print $2}' | sort | uniq); do
+for ip in $($SCOPE | grep 'm="failed authentication attempt"' | awk -F 'remote=| cid' '{print $2}' | sort | uniq); do
     case "$ip" in
-    $DONTBLOCK)
+    "$DONTBLOCK")
         continue
         ;;
     *)
@@ -158,8 +168,8 @@ for ip in $($SCOPE | grep "mox.*failed auth" | awk -F 'remote=| cid' '{print $2}
         # Unless iptables has been flushed recently, this will always be false
         if ! iptables -C INPUT -j DROP -s "$ip" >/dev/null 2>&1; then
             iptables -A INPUT -j DROP -s "$ip"
-            logger "mox failed auth DROP $ip"
-            let COUNT++
+            logger "mox: failed auth attempt DROP $ip"
+            COUNT=$((COUNT + 1))
         fi
         ;;
     esac
@@ -168,7 +178,7 @@ done
 # mail system, spf violators - all are attacks on our domains or spoofs of legit biz
 for ip in $($SCOPE | grep "mox.*spf fail.*your ip" | awk -F 'your ip | is not' '{print $2}' | sort | uniq); do
     case "$ip" in
-    $DONTBLOCK)
+    "$DONTBLOCK")
         continue
         ;;
     *)
@@ -177,7 +187,7 @@ for ip in $($SCOPE | grep "mox.*spf fail.*your ip" | awk -F 'your ip | is not' '
         if ! iptables -C INPUT -j DROP -s "$ip" >/dev/null 2>&1; then
             iptables -A INPUT -j DROP -s "$ip"
             logger "mox spf fail DROP $ip"
-            let COUNT++
+            COUNT=$((COUNT + 1))
         fi
         ;;
     esac
@@ -186,7 +196,7 @@ done
 # mail system, dnsbl rejects, often for malware
 for ip in $($SCOPE | grep "mox.*rejecting due to listing in dnsbl.*Listed by CSS" | awk -F'/ip/|\" mailfrom' '{print $2}' | sort | uniq); do
     case "$ip" in
-    $DONTBLOCK)
+    "$DONTBLOCK")
         continue
         ;;
     *)
@@ -195,7 +205,7 @@ for ip in $($SCOPE | grep "mox.*rejecting due to listing in dnsbl.*Listed by CSS
         if ! iptables -C INPUT -j DROP -s "$ip" >/dev/null 2>&1; then
             iptables -A INPUT -j DROP -s "$ip"
             logger "mox dnsbl reject DROP $ip"
-            let COUNT++
+            COUNT=$((COUNT + 1))
         fi
         ;;
     esac
@@ -205,93 +215,87 @@ done
 # To install to cron.hourly run:
 #   dropips install
 
-# static list of noted bad actors
-BADACTORS=(
-    # hacks or worse
-    "77.221.157.109" # de bitcoin intrusion/miner hack noted elsewhere
-    # prolific spammers
-    "194.169.175.0/24"   # gb emanuelhosting
-    "102.210.41.0/24"    # ke bitcoin porn scam
-    "176.88.185.0/24"    # tr bitcoin porn scam
-    "179.152.0.0/14"     # br porn bitcoin scam
-    "186.33.88.128/25"   # do bitcoin porn scam
-    "190.42.0.0/17"      # pe bitcoin porn scam
-    "196.176.0.0/14"     # tn bitcoin porn scam
-    "41.211.128.0/19"    # ga porn bitcoin scam
-    "103.164.146.0/24"   # ph bitcoin porn scam
-    "103.131.104.225/23" # id porn hack scam
-    "105.240.0.0/8"      # za porn hack scam
-    "105.0.0.0/16"       # za porn hack scam
-    "213.202.192.0/18"   # de myloc.de gummies
-    "217.79.176.0/20"    # de myloc.de gummies
-    "89.163.128.0/17"    # de myloc.de gummies
-    "46.165.192.0/18"    # de leaseweb gummies
-    "178.162.128.0/18"   # nl leaseweb
-    "62.212.64.0/19"     # nl leaseweb
-    "212.32.224.0/19"    # nl leaseweb
-    "185.49.69.0/24"     # gb leaseweb
-    "37.48.64.0/18"      # nl leaseweb
-    "5.79.64.0/18"       # nl leaseweb
-    "81.171.0.0/19"      # nl leaseweb
-    "83.149.64.0/18"     # nl leaseweb
-    "37.48.64.0/18"      # nl leaseweb
-    "62.210.0.0/16"      # fr Scaleway hosts malware, dns blocklisted
-    "163.172.0.0/16"     # fr Scaleway hosts malware, dns blocklisted
-    "200.75.0.0/19"      # cl spam hosts
-    "192.119.160.0/20"   # us "madgenius.com" scam sender
-    "155.94.191.0/24"    # us "madgenius.com" scam sender
-    "23.95.37.0/25"      # us dumb scammer
-    "165.140.240.0/22"   # us alphavps scam sender
-    "109.71.254.0/24"    # de emeraldhost.de apple ID phishing scammer
-    "41.61.0.0/17"       # hu grindhost - canadapost/intelcom phishing scammer; viagra
-    "77.87.208.0/21"     # ru bad spam, now covered by country block
-    "31.28.27.0/24"      # ru bad spam, now covered by country block
-    "5.104.104.0/21"     # de male gummies
-    "187.20.0.0/14"      # br spoofs outlook.com
-    "102.130.120.0/24"   # za purolator, intelexprescom scam
-    "185.75.240.0/24"    # uk, garden variety ru oriented scam
-    "103.4.188.0/24"     # bn fraud scam email@paulgam.com
-    "89.185.84.0/24"     # ru not currently covered by country block
-    # fraud spam sent to honeypot addresses
-    "77.87.208.0/21" # ru not currently covered by country block
-    "31.28.27.0/24"  # ru not currently covered by country block
-    "23.95.37.0/25"  # chicagovps.net
-
-    # notable smtp connections without purpose or no tls (always bad actors)
-    "193.222.96.0/24" # fr contantmoulin, 4000 connections over several days
-    "80.76.49.0/24"   # fr
-    "43.158.217.0/24" # sg
-    "45.125.66.0/25"  # hk
-    # ru not in country block at discovery
-    "62.173.128.0/19" # ru junk sales spam, spacenet
-    # cn not in country block at discovery
-    "43.143.0.0/16" # cn - donation fraud - tencent cloud computing
-
-    # auth violators
-    "111.0.0.0/10"   # cn - china mobile
-    "27.115.0.0/17"  # cn - china unicom
-    "80.244.11.0/24" # ir - iran posing as nl
-    # spf and dmarc violators
-    "191.180.0.0/14"  # br
-    "103.31.179.0/24" # bd
-    "149.54.32.0/24"  # zz afghanistan
-    # # msedge.exe / exploit
-    "212.102.40.0/23" # uk /dallas us
-    # dnsbl / obvious spammers
-    "92.53.111.0/24"  # ru, apparently outside of current country block
-    "143.110.166.49"  # digitalocean yerembe.com
-    "159.89.8.234"    # digitalocean homeofficehaven.net reg'd in iceland
-    "167.99.200.210"  # digitalocean adamdugan.com spf pass malware
-    "209.97.180.160"  # digitalocean cakechange.com reg'd in iceland
-    "165.227.221.227" # digitalocean malware sender, reported, no action by them
-    "62.4.0.0/19"     # fr scaleway
-    # many connections for no purpose
-)
-
-for ip in "${BADACTORS[@]}"; do
+# static list of noted bad actors ranging from frauds/scams to prolific spammers like leaseweb
+# or hosts that repeatedly are reported for malware
+BADACTORS="77.221.157.109
+102.210.41.0/24
+176.88.185.0/24
+179.152.0.0/14
+186.33.88.128/25
+190.42.0.0/17
+196.176.0.0/14
+41.211.128.0/19
+103.164.146.0/24
+103.131.104.225/23
+105.240.0.0/8
+105.0.0.0/16
+213.202.192.0/18
+217.79.176.0/20
+89.163.128.0/17
+46.165.192.0/18
+178.162.128.0/18
+62.212.64.0/19
+212.32.224.0/19
+185.49.69.0/24
+37.48.64.0/18
+5.79.64.0/18
+81.171.0.0/19
+83.149.64.0/18
+37.48.64.0/18
+62.210.0.0/16
+163.172.0.0/16
+200.75.0.0/19
+192.119.160.0/20
+155.94.191.0/24
+23.95.37.0/25
+165.140.240.0/22
+109.71.254.0/24
+41.61.0.0/17
+77.87.208.0/21
+31.28.27.0/24
+5.104.104.0/21
+187.20.0.0/14
+102.130.120.0/24
+185.75.240.0/24
+103.4.188.0/24
+89.185.84.0/24
+77.87.208.0/21
+31.28.27.0/24
+23.95.37.0/25
+193.222.96.0/24
+80.76.49.0/24
+43.158.217.0/24
+45.125.66.0/25
+62.173.128.0/19
+43.143.0.0/16
+111.0.0.0/10
+27.115.0.0/17
+80.244.11.0/24
+191.180.0.0/14
+103.31.179.0/24
+149.54.32.0/24
+212.102.40.0/23
+92.53.111.0/24
+143.110.166.49
+159.89.8.234
+167.99.200.210
+209.97.180.160
+165.227.221.227
+62.4.0.0/19
+"
+# newline to loop through badactors
+set -f
+IFS='
+'
+for ip in $BADACTORS; do
+    # in case of expansion needs in the loop
+    set +f
+    unset IFS
     case $ip in
-    $DONTBLOCK)
-        iptables -C INPUT -j ACCEPT -s "$ip" >/dev/null 2>&1 || iptables -I INPUT -s "$ip" -j ACCEPT
+    "$DONTBLOCK")
+        if ! iptables -C INPUT -j ACCEPT -s "$ip" >/dev/null 2>&1; then
+            iptables -I INPUT -s "$ip" -j ACCEPT
+        fi
         continue
         ;;
     *)
@@ -299,10 +303,13 @@ for ip in "${BADACTORS[@]}"; do
         if ! iptables -C INPUT -j DROP -s "$ip" >/dev/null 2>&1; then
             iptables -A INPUT -j DROP -s "$ip"
             logger "mox known bad actors DROP $ip"
-            let COUNT++
+            COUNT=$((COUNT + 1))
         fi
         ;;
     esac
 done
+# again in case there were none
+set +f
+unset IFS
 
 logger "$SCRIPT finished, $COUNT DROP rules added"
